# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-26 16:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TenhouWgGame',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(db_index=True)),
                ('game_id', models.CharField(max_length=64)),
                ('game_type', models.IntegerField()),
                ('start_time', models.CharField(max_length=8)),
                ('creation_datetime', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='TenhouWgPlayer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=64)),
                ('dan', models.IntegerField()),
                ('rate', models.FloatField()),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wg_logs.TenhouWgGame')),
            ],
        ),
    ]
